[package]
name = "creacowo/synctween"
description = "A rich TweenService replication module."
version = "1.0.7"
license = "GPL-3.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"